DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 
  TEST:
    BATCH_SIZE: 
  NUM_WORKERS: 

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0025
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_TYPE: "constant"
  WARMUP_EPOCH: 1
  WARMUP_CONS_LR: 5e-5

OPTIM1:
  NAME: "sgd"
  LR: 0.0045
  MAX_EPOCH: 
  LR_SCHEDULER: "cosine"
  WARMUP_TYPE: "constant"
  WARMUP_EPOCH: 1
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

TEST:
  NO_TEST: False

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  AdaCPI:
    N_CTX: 2
    CTX_INIT: "a photo of a"
    PREC: "fp16"
    FUSION_DEPTH: None
    ADAPTIVE_FUSION: True
    W: 0.1
    TEMPERATURE: 5.0
